/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class frc_robot_Drive_TinyMPCJNI */

#ifndef _Included_frc_robot_Drive_TinyMPCJNI
#define _Included_frc_robot_Drive_TinyMPCJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     frc_robot_Drive_TinyMPCJNI
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_Drive_TinyMPCJNI_initializeNative
  (JNIEnv *, jclass);

/*
 * Class:     frc_robot_Drive_TinyMPCJNI
 * Method:    solve
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_frc_robot_Drive_TinyMPCJNI_solveNative
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
