/*
 * This file was autogenerated by TinyMPC on Thu May 14 18:37:09 2026
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_solver;

#ifdef __cplusplus
}
#endif
