name: Visualize States

on:
  pull_request:
    types:
      - reopened
      - opened
      - synchronize

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install graphviz

    - name: Run graph generation
      id: run-script
      run: |
        python3 .github/scripts/visualizeStates.py ./src/main/java/frc/robot/Subsystems/Manager/ManagerStates.java ./src/main/java/frc/robot/Subsystems/Manager/Manager.java
        echo "exit_code=$?" >> $GITHUB_OUTPUT
      continue-on-error: true

    - name: Upload graph as artifact
      uses: actions/upload-artifact@v4
      with:
        name: state-machine-graph
        path: state_machine.png

    - name: Comment on PR
      uses: actions/github-script@v6
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          const exitCode = Number(process.env.EXIT_CODE);
          const commentBody = exitCode === 0
              ? "✅ State machine graph generated and uploaded."
              : "⚠️ Something went wrong while generating the state machine graph.";

          github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: commentBody
          })
      env:
        EXIT_CODE: ${{ steps.run-script.outputs.exit_code }}